
export const LOAD_PRODUCTS = 'LOAD_TUNINGS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const FETCH_VIDEOS = 'FETCH_VIDEOS'
export const SELECTED_VIDEO = 'SELECTED_VIDEO'

